### ISSUE TITLE
Add the ability to lock other menus besides for the whole OS

### ISSUE THREAD

**Issue by scooterthedev** [X1Plus/X1Plus#133] opened 2024-03-28 19:26 UTC
**Describe the solution you'd like**
Right now, we can only lock the whole device. Is it possible to make it so we can lock the main 4 menus individually too? It would be used for, if for example I would like someone to access the print cache menu, but not anything else.

**Software Information**
 - Current X1Plus Version: 1.0

**Additional context**
Add an option in the lock area, for what menu you want to lock too.

**Comment by RobinWhitfield** [comment] 2024-03-28 20:46
Duplicate of #68

**Closed by RobinWhitfield** 2024-03-28 20:46 UTC
Labels: enhancement
